apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-hello  
  template:
    metadata:
      labels:
        app: nodejs-hello
    spec:
      containers:
      - name: node-hello
        image: thejchaves/node-hello:0.1
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: nodejs-hello
  ports:
    - port: 80
      targetPort: 3000
  externalTrafficPolicy: Local
  type: LoadBalancer
